ALTER TABLE [core].[Country] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[Currency] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[DomainType] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[DomainValue] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[Product] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[Stock] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[Tenant] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[User] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserGroup] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserRight] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserRightsRole] WITH CHECK CHECK CONSTRAINT ALL;
GO

