ALTER TABLE [core].[Country] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[Currency] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[DomainType] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[DomainValue] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[Product] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[Stock] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[Tenant] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[User] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserGroup] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserRight] NOCHECK CONSTRAINT ALL;
ALTER TABLE [core].[UserRightsRole] NOCHECK CONSTRAINT ALL;
GO

